@startuml


package "ft_Transcendance" {

    [Makefile] as Makefile
    [docker-compose.yml] as DockerCompose
    [.env] as Env

    folder <<nginx>>  #Aquamarine;line:SkyBlue;line.bold{
        [Dockerfile] as NginxDockerfile
        [default.conf] as NginxConf
    }

    package "srcs" {
        folder backend #AntiqueWhite;line:GoldenRod;line.bold {
        }
        folder frontend #AliceBlue;line:Blue;line.bold {
       }

    }
}

note top of Env: Environment variables for the project.
note bottom of NginxConf: Configuration file for NGINX, which defines how the server handles incoming requests.  
note top of Makefile: Execute all environement and docker scripts in an easy and fast way

@enduml